# This indicates to Travis that we will not use or need sudo
# so that we can benefit from and use the cache->directories
# directive.
sudo: no

env: PIP_DOWNLOAD_CACHE="pip_cache"
cache:
    directories:
        - pip_cache

language: python

before_install:
  - travis_retry pip install tox coveralls

install:
  - travis_retry python setup.py install

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=pypy

script:
  - tox -e $TOX_ENV

after_success:
  # Report coverage results to coveralls.io
  - coveralls
